import Head from "next/head";
import "./styles/globals.css";
import { Inter } from "next/font/google";
import { Footer, Navbar } from "./Components";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <div className='layout'>
        <Head>
          <title>E-Commerce</title>
        </Head>
        <header>
          <Navbar />
        </header>
        <main className='main-container'>{children}</main>
        <footer>
          <Footer />
        </footer>
      </div>
    </html>
  );
}
