import "./styles/globals.css";
import { Inter } from "next/font/google";
import { Footer, Navbar } from "./Components";
import { StateContext } from "../../ecommerce/context/StateContext";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <StateContext>
      <html lang='en'>
        <head>
          <title>E-Commerce</title>
        </head>
        <body>
          <div className='layout'>
            <header>
              <Navbar />
            </header>
            <Toaster />
            <main className='main-container'>{children}</main>
            <footer>
              <Footer />
            </footer>
          </div>
        </body>
      </html>
    </StateContext>
  );
}
