import "./styles/globals.css";
import { Footer, Navbar } from "./components";
import { StateContext } from "./context/StateContext";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <StateContext>
      <html lang='en'>
        <head>
          <title>E-Commerce</title>
        </head>
        <body>
          <div className='layout'>
            <header>
              <Navbar />
            </header>
            <Toaster />
            <main className='main-container'>{children}</main>
            <footer>
              <Footer />
            </footer>
          </div>
        </body>
      </html>
    </StateContext>
  );
}
